homeworks:
  host: 192.168.2.55
  port: 4008

light:  
  - platform: homeworks
    dimmers:
      - addr: "[02:08:01:15]"
        name: "Lower Stairs"
        rate: 5
      - addr: "[02:08:01:25]"
        name: "Upper Stairs"

binary_sensor:
  - platform: homeworks
    keypads:
      - addr: "[02:08:02:05]"
        name: "Family Room Keypad"
        buttons:
            0: "Button1"
            1: "Button2"
      - addr: "[02:08:02:02]"
        name: "Kitchen Keypad"
        buttons:
            0: "Button1"
 


