# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up Python 3.12
        uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          pip install -r requirements-test.txt
      - name: Lint with flake8
        run: |
          flake8 pyhomeworks
      - name: Check formatting with black
        run: |
          black pyhomeworks --check --diff
      - name: Lint with mypy
        run: |
          mypy pyhomeworks
      - name: Lint with pylint
        run: |
          pylint pyhomeworks
